name: Report-Metrics
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |     
          echo "# Metrics" > report.md
          
          
          cml send-comment report.md