name: Report-Metrics
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |    
          if [ -e notebooks/reports/report.txt] 
          then
            cat notebooks/reports/report.txt > report.md
          fi

          if [ notebooks/reports/confusion_matrix.png ]
          then
            echo "# Confusion Matrix" >> report.md
            cml publish notebooks/reports/confusion_matrix.png --md >> report.md
          fi

          if [ notebooks/reports/causal_graph.png ]
          then
            echo "# Causal Graph" >> report.md
            cml publish notebooks/reports/causal_graph.png --md >> report.md
          fi
          
          
          cml send-comment report.md